CREATE TABLE IF NOT EXISTS project
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(150) NOT NULL,
  content TEXT NOT NULL,
  repo VARCHAR(150),
  url VARCHAR(150),
  publishedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
